apiVersion: apps/v1
kind: Deployment
metadata:
  name: environment-simulator
spec:
  replicas: 5
  selector:
    matchLabels:
      app: env-sim
  template:
    metadata:
      labels:
        app: env-sim
    spec:
      containers:
      - name: env-sim-container
        image: rukasu/environment-variables-simulator:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: env-sim-service
spec:
  selector:
    app: env-sim
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    nodePort: 30000
